version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: tira-postgres
      POSTGRES_PASSWORD: tira-password
      POSTGRES_DB: tira-db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root  # để Jenkins có quyền mount docker.sock
    env_file:
      - /home/checkingapp/tira/.env
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # mount Docker host
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: phantansy/tira-be:latest
    container_name: tira-container
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - /home/checkingapp/tira/.env:/app/.env  # mount file .env trực tiếp
       
volumes:
  pgdata:
  jenkins_home:
  tira_data:

networks:
  app-network:
    driver: bridge
