version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tira-be
    restart: always
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:
  jenkins_home:

networks:
  app-network:
    driver: bridge
